ELDEN_RING = {
    "ATTRIBUTES": {
        "Vigor": {},
        "Mind": {},
        "Endurance": {},
        "Strength": {},
        "Dexterity": {},
        "Intelligence": {},
        "Faith": {},
        "Arcane": {},
    },
    "WEAPON_CATEGORIES": {
        "Axes": {},
        "Ballistae": {},
        "Bows": {},
        "Claws": {},
        "Colossal Swords": {},
        "Colossal Weapons": {},
        "Crossbows": {},
        "Curved Greatswords": {},
        "Curved Swords": {},
        "Daggers": {},
        "Fists": {},
        "Flails": {},
        "Glintstone Staffs": {},
        "Greataxes": {},
        "Greatbows": {},
        "Great Spears": {},
        "Greatswords": {},
        "Halberds": {},
        "Hammers": {},
        "Heavy Thrusting Swords": {},
        "Katanas": {},
        "Light Bows": {},
        "Reapers": {},
        "Sacred Seals": {},
        "Spears": {},
        "Straight Swords": {},
        "Thrusting Swords": {},
        "Torches": {},
        "Twinblades": {},
        "Great Hammers": {},
        "Whips": {},
    },
    "CLASSES": {
        "Hero": {},
        "Bandit": {},
        "Astrologer": {},
        "Warrior": {},
        "Prisoner": {},
        "Confessor": {},
        "Wretch": {},
        "Vagabond": {},
        "Prophet": {},
        "Samurai": {},
    },
}
